Repository Wanted-Pre-Onboarding-Frontend-2/wonflix, pull requests merged in 2022-07, with the labels that each got.

#12 [#11]feat: add favorite movie data
  package.json
  public/data/movies.json
  src/api/useGetMovie.js
  src/components/Favorites/Favorites.jsx
  src/routes/Favorites/Favorites.jsx
  yarn.lock
Labels: feat

#16 feat: create movie card
  src/components/Modal/Modal.jsx
  src/components/Modal/index.jsx
  src/components/Modal/modal.scss
  src/components/MovieList/MovieList.jsx
  src/components/MovieList/index.jsx
  src/components/Portal.jsx
  src/routes/Home/Home.jsx
  src/routes/index.jsx
  src/store/modal.jsx
  src/store/search.js
Labels: feat

#20 fix: fix home routing
  src/routes/index.jsx
Labels: fix

#38 [#26] feat: add favorite api, change favorite card design
  src/api/useUpdateFavorite.js
  src/components/Favorites/Favorites.jsx
  src/components/Movies/Card/Card.jsx
  src/components/Movies/Card/card.scss
  src/components/Movies/index.jsx
  src/components/Movies/movies.scss
  src/components/Search/SearchForm/SearchForm.jsx
  src/data/movies.json
  src/store/movies.js
  src/store/search.js
Labels: feat

#40 [#39] fix: change favorite api axios (put -> patch)
  src/api/useUpdateFavorite.js
  src/components/Movies/Card/Card.jsx
Labels: fix

#49 feat: sort css
  src/api/config.js
  src/api/useGetMovie.js
  src/api/useSearch.js
  src/api/useSortMovie.js
  src/api/useUpdateFavorite.js
  src/components/Movies/MovieSort/MovieSort.jsx
  src/components/Movies/MovieSort/movieSort.scss
  src/components/Movies/index.jsx
  src/components/Movies/movies.scss
  src/store/search.js
Labels: feat

#50 fix: remove search.js movieData
  src/components/Movies/Card/Card.jsx
  src/components/Movies/index.jsx
  src/components/Search/Dropdown/Dropdown.jsx
  src/components/Search/Dropdown/DropdownItems.jsx
  src/components/Search/SearchForm/SearchForm.jsx
  src/store/search.js
Labels: fix

#68 [#55]fix: change api structure
  src/api/useFetchData.js
  src/api/useGetMovie.js
Labels: fix

#78 [#77] documentation: update reademe
  README.md
Labels: documentation
